name: 🐱 CatOS Rolling CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-bootloader:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Скачиваем код
      uses: actions/checkout@v4

    - name: Устанавливаем NASM
      run: |
        sudo apt update
        sudo apt install -y nasm

    - name: Компилируем CatOS (Загрузчик + Ядро)
      run: |
        mkdir -p release_assets
        # 1. Собираем загрузчик
        nasm -f bin src/boot.asm -o release_assets/boot.bin
        # 2. Собираем ядро
        nasm -f bin src/kernel.asm -o release_assets/kernel.bin
        # 3. Склеиваем их в финальный образ диска для QEMU/Rufus
        cat release_assets/boot.bin release_assets/kernel.bin > release_assets/os.img

    - name: Пересоздать тег main
      shell: bash
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git tag -d main || true
        git push origin :refs/tags/main || true
        sleep 3
        git tag main
        git push origin refs/tags/main --force

    - name: Загружаем результат в Релиз
      uses: softprops/action-gh-release@v2
      with:
        tag_name: main
        files: release_assets/*
        name: "main"
        overwrite: true
        prerelease: false
        body: |
          🐾 The latest image of the CatOS operating system.
          The `main` tag is automatically recreated every time the repository is pushed.
          
          Inside the archive:
          - `os.img` - Full operating system image (Bootloader + Kernel). Perfect for QEMU and Rufus!
          - `boot.bin` and `kernel.bin` - Separate binaries for low-level tests.
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
